name: 'Moddable Prebuild'
description: 'Generate release artifacts of Moddable tooling for each supported platform'
inputs:
  commit:  # id of input
    description: 'Which commit to build'
    required: true
    default: 'latest'
outputs:
  tag:
    description: 'Tag of build artifacts'
  artifactName:
    description: 'Name of artifact tarball'
runs:
  using: 'node16'
  main: 'dist/index.js'
