name: Build Moddable tooling

on:
  - push
  - workflow_dispatch

jobs:
  build_tools:
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - run: npm ci
      - run: npm run build

      - name: Clone and build tooling
        uses: ./
        id: prebuild

      - name: Push release
        uses: softprops/action-gh-release@v1
        with:
          name: v1
          tag_name: v1
          files: |
            moddable/build/bin/**/release/*
