name: Build Moddable tooling

on:
  push:
    branches:
      - 'windows-support'
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      commit:
        description: 'Which commit to build for Moddable repo'
        required: false
        type: string
        default: 'latest'


jobs:
  build_tools:
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - run: npm ci
      - run: npm run build

      - uses: ilammy/msvc-dev-cmd@v1
      
      - name: Clone and build tooling
        uses: ./
        id: prebuild
        with:
          commit: ${{ github.event.inputs.commit }}

      - name: Push release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.prebuild.outputs.tag }}
          tag_name: latest
          files: |
            ${{ steps.prebuild.outputs.artifactName }}
